// Jira Software Data Center REST API Reference MCP server — generated by mcpify. Do not hand-edit.

use jira_dc_mcp::core::config_manager::load_config;
use jira_dc_mcp::core::sanitizer::sanitize;

pub fn run() -> anyhow::Result<()> {
    let config = load_config(serde_json::Map::new())?;
    let sanitized = sanitize(&serde_json::to_value(&config)?);
    println!("{}", serde_json::to_string_pretty(&sanitized)?);
    Ok(())
}
