// Jira Software Data Center REST API Reference MCP server — generated by mcpify. Do not hand-edit.

use crate::auth::auth_manager::AuthManager;
use crate::auth::request_credentials::RequestCredentials;
use crate::core::config_schema::Config;
use crate::data::store::EndpointRecord;
use crate::services::api_client::ApiClient;
use crate::validation::validator::{validate_input, validate_output};

/// Validates arguments against the input schema, injects the active auth
/// strategy's credentials, executes the live HTTP request, and checks the
/// response against the output schema before returning it — PRD §1.5's
/// `call` pipeline (architecture.md's 4-step `call` pipeline).
///
/// An output-schema mismatch is only logged, not raised: real-world OpenAPI
/// specs (e.g. Atlassian's published Jira Data Center spec) are frequently
/// wrong about response shape — declaring a single object where the API
/// actually returns an array, or an overly narrow `additionalProperties`
/// for a free-form bag of fields — and rejecting an otherwise-successful
/// call over a documentation bug would deny the caller real data it
/// already has in hand. Input validation still hard-fails: those arguments
/// are under the caller's control, not the upstream API's.
///
/// Takes an already-looked-up `EndpointRecord` rather than a `Connection`
/// and an `operation_id` to look up itself: `rusqlite::Connection` isn't
/// `Sync`, so a `&Connection` held across this function's `.await` points
/// (the HTTP call) would make the caller's future non-`Send` — a hard
/// requirement for `#[tool]` methods (Story R6). Callers look the
/// endpoint up (a synchronous, `Connection`-scoped step) before calling
/// this function, not inside it.
pub async fn call_operation(
    endpoint: &EndpointRecord,
    config: &Config,
    auth_manager: &mut AuthManager,
    operation_id: &str,
    args: serde_json::Value,
    request_override: Option<&RequestCredentials>,
) -> anyhow::Result<serde_json::Value> {
    validate_input(&config.api_version, operation_id, &args)?;

    let client = ApiClient::new(config.clone());
    let response = client
        .execute(endpoint, &args, auth_manager, request_override)
        .await?;

    if let Err(err) = validate_output(&config.api_version, operation_id, &response) {
        tracing::warn!(
            operation_id,
            error = %err,
            "response did not match the documented schema; returning it as-is"
        );
    }
    Ok(response)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::config_schema::AuthMethod;
    use tokio::io::{AsyncReadExt, AsyncWriteExt};
    use tokio::net::TcpListener;

    #[tokio::test]
    async fn call_operation_executes_against_test_server() {
        let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
        let address = listener.local_addr().unwrap();

        let handle = tokio::spawn(async move {
            if let Ok((mut stream, _)) = listener.accept().await {
                let mut buf = [0u8; 1024];
                let _ = stream.read(&mut buf).await;
                let body = r#"{"status":"ok"}"#;
                let response = format!(
                    "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{}",
                    body.len(),
                    body
                );
                let _ = stream.write_all(response.as_bytes()).await;
            }
        });

        let endpoint = EndpointRecord {
            operation_id: "testOp".to_string(),
            path: "/test".to_string(),
            method: "GET".to_string(),
            summary: None,
            description: None,
            input_schema: serde_json::json!({}),
            output_schema: serde_json::json!({}),
            auth_scheme_ref: None,
        };

        let config: Config = serde_json::from_value(serde_json::json!({
            "url": format!("http://{address}"),
            "auth_method": "basic",
            "timeout_ms": 1000
        }))
        .unwrap();

        let mut auth_manager = AuthManager::new(AuthMethod::Basic);
        auth_manager.set_credentials(crate::auth::auth_strategy::Credentials::from([(
            "authorization_header".to_string(),
            "Basic test".to_string(),
        )]));

        let res = call_operation(
            &endpoint,
            &config,
            &mut auth_manager,
            "testOp",
            serde_json::json!({}),
            None,
        )
        .await
        .unwrap();

        assert_eq!(res["status"], "ok");
        handle.await.unwrap();
    }
}


