//! MCP prompts: guided Jira Data Center management workflows. See
//! `docs/mcp-prompts-workflow-plan.md` for the design this module implements.
//!
//! Hand-authored (not generated by mcpify) -- kept separate from `tools/`.

pub mod router;

use rmcp::schemars;
use serde::Deserialize;

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct MasterWorkflowArgs {
    /// What the user is trying to accomplish, in their own words
    pub goal: Option<String>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct IssuesWorkflowArgs {
    /// Key of the project to create or act on an issue in (e.g. "PROJ")
    pub project_key: Option<String>,
    /// Issue type to create (e.g. "Bug", "Task", "Story")
    pub issue_type: Option<String>,
    /// Summary/title for a new issue
    pub summary: Option<String>,
    /// Key of an existing issue to act on (e.g. "PROJ-123")
    pub issue_key: Option<String>,
}

/// Renders a short "what's already known" header to prepend to a prompt's
/// static markdown body, so its step-by-step instructions can tell the
/// calling LLM exactly which parameters still need to be asked for instead
/// of re-deriving that from the raw arguments every time.
pub fn render_context_header(fields: &[(&str, Option<&str>)]) -> String {
    let provided: Vec<String> = fields
        .iter()
        .filter_map(|(name, value)| value.map(|v| format!("- {name}: {v}")))
        .collect();
    let missing: Vec<String> = fields
        .iter()
        .filter(|(_, value)| value.is_none())
        .map(|(name, _)| format!("- {name}"))
        .collect();

    let mut out = String::from("## Context already provided\n");
    if provided.is_empty() {
        out.push_str("(none)\n");
    } else {
        out.push_str(&provided.join("\n"));
        out.push('\n');
    }
    if !missing.is_empty() {
        out.push_str(
            "\n## Still needed -- ask the user for these if the flow below requires them\n",
        );
        out.push_str(&missing.join("\n"));
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_field_list_renders_only_the_provided_header() {
        let header = render_context_header(&[]);
        assert_eq!(header, "## Context already provided\n(none)\n");
    }

    #[test]
    fn all_supplied_fields_are_listed_with_no_missing_section() {
        let header = render_context_header(&[("goal", Some("set up a dead-letter queue"))]);
        assert!(header.contains("- goal: set up a dead-letter queue"));
        assert!(!header.contains("Still needed"));
    }

    #[test]
    fn all_missing_fields_produce_no_provided_lines_but_list_every_field() {
        let header = render_context_header(&[("project_key", None), ("issue_type", None)]);
        assert!(header.contains("(none)"));
        assert!(header.contains("Still needed"));
        assert!(header.contains("- project_key"));
        assert!(header.contains("- issue_type"));
    }

    #[test]
    fn mixed_fields_split_correctly_between_provided_and_missing() {
        let header = render_context_header(&[
            ("project_key", Some("PROJ")),
            ("issue_type", None),
            ("summary", Some("Fix the thing")),
            ("issue_key", None),
        ]);
        assert!(header.contains("- project_key: PROJ"));
        assert!(header.contains("- summary: Fix the thing"));
        assert!(header.contains("Still needed"));
        assert!(header.contains("- issue_type"));
        assert!(header.contains("- issue_key"));
        assert!(!header.contains("- project_key\n"));
    }
}
